-   id: pyproject-to-requirements
    name: pyproject-to-requirements
    description: Sync pyproject & requirements.txt.
    entry: pyproject-to-requirements
    language: python
    files: pyproject\.toml$
    types: [text]
